### ISSUE TITLE
TypeError: dynamo.define(...).withGlobalIndex is not a function

### ISSUE THREAD

**Issue by rudieros** [lucasmafra/type-dynamo#4]
Hello!

I would like to report a possible bug. I get the error `TypeError: dynamo.define(...).withGlobalIndex is not a function` when defining my table with an index.
Here is my table definition:
```typescript
const dynamo = new TypeDynamo({ region: process.env.region || 'us-east-1' })

const userRepo = dynamo.define(UserTable, {
  tableName: UserSchema.tableName,
  partitionKey: 'id',
}).withGlobalIndex({
  indexName: 'emailIndex',
  partitionKey: 'email',
  projectionType: 'ALL',
}).getInstance()
```

and here is my UserTable class
```typescript
 export class UserTable {
  id: string
  username: string
  name: string
  email: string
}
```

I believe the error comes from the file src/schema/type-dynamo/type-dynamo.ts, where your implementation of the function `TypeDynamo.define` returns a `DynamoTableWithSimpleKey` instead of a `TypeDynamoDefineTableSimpleKey`.
```typescript
        if (schema.sortKey !== undefined) {
            return new TypeDynamoDefineTableCompositeKey(this.dynamoPromise, schema).getInstance() as any
        }
        return new TypeDynamoDefineTableSimpleKey(this.dynamoPromise, schema).getInstance() as any
```

probably because of the getInstance()? Let me know if I am doing something wrong, that might well be the case!

Great lib by the way!

**Comment by lucasmafra** [comment]
hi @rudieros, thanks for reporting this issue. You're right, the ```define()``` method should not call the ```getInstance()```. This bug is fixed in v0.1.3 so I'm closing this issue.
