### ISSUE TITLE
query operation not working properly

### ISSUE THREAD

**Issue by henriqueguisasola** [lucasmafra/type-dynamo#7]
## Current Behavior
When i try to query, using any sortKeyCondition and error is thrown:

```
{ ValidationException: Invalid KeyConditionExpression: An expression attribute name used in the document path is not defined; attribute name: #pff79e8cns
```

## Possible Solution
Apparently, the table schema definition, for CompositeKey is not adding the sort key do it's `TableSchema` object

## Steps to Reproduce
1. 
```
private repo = typeDynamo.define(UserRelationTable, {
    tableName: TABLE_NAME,
    partitionKey: 'id',
    sortKey: 'sort'
  }).getInstance()
```

2.
```
 const dbResult = await this.repo.find({ id })
      .withSortKeyCondition(beginsWith('test'))
      .execute()
```

## Detailed Description
Add the sort key to the `TableSchema` when creating the CompositeKey table

## Possible Implementation
Change the `buildTableSchema` function in `src/schema/type-dynamo/define-table/composite-key/composite-key.ts` to:

```
private buildTableSchema(schema: any): TableSchema {
        const tableSchema: TableSchema = {
            tableName: schema.tableName,
            partitionKey: schema.partitionKey,
            sortKey: schema.sortKey,
            writeCapacity: schema.writeCapacity || 1,
            readCapacity: schema.readCapacity || 1,
        }
        return tableSchema
    }
```

**Comment by lucasmafra** [comment]
Hi @henriqueguisasola 

Fixed on https://github.com/lucasmafra/type-dynamo/commit/96d7534ade90317379aeb1d02e316ac89c8bbf96 and released at [v0.1.5](https://npmjs.com/package/type-dynamo)

Thanks for the implementation suggestion.
